### ISSUE TITLE
Emacs 26.3: list-packages shows poetry.el as incompatible

### ISSUE THREAD

**Issue by jerryasher** [cybniv/poetry.el#19] opened 2020-05-14 22:03 UTC
poetry             0.1.0         incompat   melpa-s... poetry in Emacs

and looking at the \*Help* buffer (details )

    poetry is an incompatible package.
    
         Status: Incompatible because it depends on uninstallable packages.
        Archive: melpa-stable
        Version: 0.1.0
         Commit: 6fb34742a66421c6104e02d65e8d391fc4494ab5
        Summary: poetry in Emacs
       Requires: transient-0.1.0, cl-1.0 (not available), xterm-color-1.8
       Homepage: https://github.com/galaunay/poetry.el
       Keywords: python tools 
    Other versions: 20200326.1328 (melpa).
    
    This package offers an interface to poetry (https://poetry.eustace.io/),
    a Python dependency management and packaging command line tool.

That said, I loaded it manually following the instructions in the readme, and it loaded with no errors, and `m-x poetry` asks me to create or init a project

**Comment by galaunay** [comment] 2020-05-27 09:49
Thanks, I didn't realised the 0.1.0 release was uninstallable.
I just released 0.2.0 so it should be fine now.

Please re-open if you still experience issues.

**Comment by crawler-n** [comment] 2024-03-28 08:45
Issue still exists with melpa stable. Version on Stable is still 0.1.0, which is incompatible because of non-existent cl 1.0 dependency.

https://stable.melpa.org/#/poetry

Is this because 0.2.0 was never tagged, so doesn't count as "stable" release?

**Comment by cybniv** [comment] 2024-03-29 10:48
pushed tag 0.2.0 now, whilst pointing to 2cbc690c8c1153e578ecb376367d355a7669f9ec

**Comment by crawler-n** [comment] 2024-03-31 23:00
Confirmed that this is now fixed. New version `0.2.0` could be installed via Melpa Stable.
Thanks for tagging the release so quickly.

**Comment by cybniv** [comment] 2024-04-01 17:18
@crawler-n Thanks for testing and confirming :)

**Closed by cybniv** 2024-04-01 17:18 UTC
